### ISSUE TITLE
Need to build twice to update docs/coverage.md with ✔

### ISSUE THREAD

**Issue by amarinelli** [AmrEldib/agol-schemas#13]

**Comment by AmrEldib** [comment]
Maybe the doc files gets built before the schema files finish generating?

**Comment by amarinelli** [comment]
Added a console.log() statement in [build/build-faker-schema.js (line 131)](https://github.com/AmrEldib/agol-schemas/blob/master/build/build-faker-schema.js#L131) and the console output proves that the docs/coverage.md file is generated before the schema's are written.

Output shows that the schema files are even written after the final ["Build complete"](https://github.com/AmrEldib/agol-schemas/blob/master/build/build.js#L12) message.

![image](https://cloud.githubusercontent.com/assets/4150021/14181021/5518211e-f733-11e5-9f51-152d428e7f7b.png)

**Comment by AmrEldib** [comment]
I wonder if we should switch to using Grunt for building. I'll try it out

**Comment by amarinelli** [comment]
Workaround: `npm run build && npm run build`

**Comment by AmrEldib** [comment]
@amarinelli Grunt didn't resolve the issue, I'm switching to using promises. It works fine so far, but I need to finish converting functions to use promises instead of callbacks. This is a good thing anyway.

**Comment by AmrEldib** [comment]
Switching to Promises didn't exactly fix the issue even though I've confirmed that build steps run sequentially. There's something else causing a problem.
Switching to Promises is a good side effect as it makes for better code
I've resolved the issue by switching to check schemas in the `schemasFolder` rather than `outputFolder`
